name: Smart_College
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  awesome_dialog: ^3.2.0
  provider: ^6.1.2
  
  vector_math: any
  cloud_firestore: ^4.16.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  dotted_border: ^2.1.0
  firebase_database: ^10.5.4
  multi_dropdown: ^2.1.4
  google_nav_bar: ^5.0.6
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  geolocator: ^12.0.0
  datetime_picker_formfield: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        #- asset: fonts/futura-no2-d-ot-medium.otf
